services:
  deploydeploydeploy:
    image: git.diffusehyperion.com/diffusehyperion/deploydeploydeploy:latest
    container_name: deploydeploydeploy
    restart: unless-stopped
    environment:
      TRAEFIK_NETWORK: deploydeploydeploy
      TRAEFIK_HTTP_ENTRYPOINT: http
      DATA_FILE: /deploydeploydeploy/data/data.sqlite
      PROJECT_DIR: /deploydeploydeploy/data/projects
      SECRET_KEY: CHANGEME
      # ENABLE_DOCS: true
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "deploydeploydeploy_data:/deploydeploydeploy/data"
  traefik:
    image: traefik:latest
    container_name: deploydeploydeploy-traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "deploydeploydeploy-traefik_data:/traefik"
networks:
  default:
    name: deploydeploydeploy
volumes:
  deploydeploydeploy_data:
    name: deploydeploydeploy_data
  deploydeploydeploy-traefik_data:
    name: deploydeploydeploy-traefik_data