services:
  deploydeploydeploy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deploydeploydeploy
    restart: unless-stopped
    environment:
      TRAEFIK_NETWORK: deploy*3
      TRAEFIK_HTTP_ENTRYPOINT: http
      DATA_FILE: /deploy*3/data.sqlite
      PROJECT_DIR: /deploy*3/projects
      SECRET_KEY: CHANGEME
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./run:/deploy*3"
  traefik:
    image: traefik:latest
    container_name: deploydeploydeploy-traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "-entrypoints.http.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./run/traefik:/traefik"
networks:
  default:
    name: deploy*3