services:
  deploydeploydeploy:
    image: git.diffusehyperion.com/diffusehyperion/deploydeploydeploy:latest
    container_name: deploydeploydeploy
    restart: unless-stopped
    environment:
      TRAEFIK_NETWORK: deploydeploydeploy
      TRAEFIK_HTTP_ENTRYPOINT: http
      TRAEFIK_HTTPS_ENTRYPOINT: https
      TRAEFIK_CERTRESOLVER: letsencrypt
      DATA_FILE: /deploydeploydeploy/data/data.sqlite
      PROJECT_DIR: /deploydeploydeploy/data/projects
      SECRET_KEY: CHANGEME
      # ENABLE_DOCS: true
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "deploydeploydeploy_data:/deploydeploydeploy/data"
  traefik:
    image: traefik:latest
    container_name: deploydeploydeploy-traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=CHANGEME@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "deploydeploydeploy-traefik_data:/traefik"
      - "deploydeploydeploy-traefik_certs:/letsencrypt"
networks:
  default:
    name: deploydeploydeploy
volumes:
  deploydeploydeploy_data:
    name: deploydeploydeploy_data
  deploydeploydeploy-traefik_data:
    name: deploydeploydeploy-traefik_data
  deploydeploydeploy-traefik_certs:
    name: deploydeploydeploy-traefik_certs