services:
  deploydeploydeploy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deploydeploydeploy
    restart: no
    environment:
      ENABLE_DOCS: true
      TRAEFIK_NETWORK: deploydeploydeploy
      TRAEFIK_HTTP_ENTRYPOINT: http
      DATA_FILE: /deploydeploydeploy/data/data.sqlite
      PROJECT_DIR: /deploydeploydeploy/data/projects
      SECRET_KEY: CHANGEME
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./run:/deploydeploydeploy/data"
  traefik:
    image: traefik:latest
    container_name: deploydeploydeploy-traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "-entrypoints.http.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./run/traefik:/traefik"
networks:
  default:
    name: deploydeploydeploy